### ISSUE TITLE
Threshold should be compared against a relative value rather than an absolute value

### ISSUE THREAD

**Issue by 0xced** [VerifyTests/Verify.ImageSharp.Compare#48]
#### Is the feature request related to a problem

Comparing the defined threshold against the `AbsoluteError` property of the comparison result doesn't make much sense since the absolute error value can greatly vary depending on the size of the image.

#### Describe the solution

Comparing the threshold against either `MeanError` or `PixelErrorPercentage` (or even both) would be preferable.

Open question: should backward compatibility with the current implementation be maintained or can I completely rewrite the methods that take `int threshold = 5` into methods that take `double meanErrorThreshold = 0, double pixelErrorPercentageThreshold = 0` instead?

#### Describe alternatives considered

N/A

#### Additional context

After upgrading the rendering engine that produces image I wanted to use`Verify.ImageSharp.Compare` to ensure that the new engine was producing similar enough images as the previous version. Some images were fine (AbsoluteError == 0) but for some other there was some slight differences that could be easily ignored. It would be possible to quantify those differences as a percentage, but not as an absolute value.

**Comment by SimonCropp** [comment]
happy to do a major with no back compat. so if u have time do fo a PR, go for it
