### ISSUE TITLE
Allow for the use of a mask when comparing images

### ISSUE THREAD

**Issue by MJB222398** [VerifyTests/Verify.ImageSharp.Compare#57]
I want to use this package in my automated system tests (for a web application) to verify screenshots. However as the tests use randomly generated usernames and other data, and the application UI has a build version stamp in it, there will be areas in the images that legitimately differ. Setting a pixel threshold does not work for me here as the version number is not always different, and if it isn't then the pixels allowed for that could be used by another component changing and I would be unaware. I would be able to have a tolerance of virtually zero if there was the ability to use a mask. I would then have quite supreme confidence that nothing had changed. What I really need to do is be able to use the 'mask' concept that ImageSharp.Compare already has. 

For each verification we would need the .verified.png file and the .verified.mask.png file (or similar). The mask file would most likely be up to the developer to create. With this the comparison could then be performed by the ImageSharpCompare.CalcDiff method.

**Comment by SimonCropp** [comment]
how are you generating the screenshots? r u using https://github.com/VerifyTests/Verify.HeadlessBrowsers  ?

**Comment by MJB222398** [comment]
> how are you generating the screenshots? r u using https://github.com/VerifyTests/Verify.HeadlessBrowsers ?

Sorry forgot to include that. I am not using that no, not using headless browsers, my tests run against a Selenium grid Docker container, so I have browsers running on Selenium nodes connected to that. I just use the Selenium driver's built in screenshot taking functionality and write those screenshots to disk as .png files. I am then using ImageSharp.Compare to compare these to references using masks but this is quite clunky in the file handling/organisation etc. As I am also using Verify (Verify.AngleSharp) to verify the html sources of the pages alongside I thought it would be nice to use Verify.ImageSharp.Compare for the screenshots too

**Comment by SimonCropp** [comment]
in that case i am happy to consider a pull request for this feature
